### ISSUE TITLE
building fails with Qt < 6.8

### ISSUE THREAD

**Issue by uncor3** [lxqt/qtermwidget#599]
Since commit f73888c6c880b9e3e98392a81a2e839f9a196a99 the project no longer builds on macOS with Qt 6.7.2

qtermwidget/lib/ColorScheme.cpp:368:26: error: no member named 'slice' in 'QStringView'; did you mean 'sliced'?
  368 |             r = colorStr.slice(1, 2).toInt(nullptr, 16); 

Qt/6.7.2/macos/lib/QtCore.framework/Headers/qstringview.h:227:41: note: 'sliced' declared here
  227 |     [[nodiscard]] constexpr QStringView sliced(qsizetype pos, qsizetype n) const noexcept

I think README should be updated 
[
"The only runtime dependency is qtbase ≥ 6.6.0."](https://github.com/lxqt/qtermwidget/blob/f73888c6c880b9e3e98392a81a2e839f9a196a99/README.md?plain=1#L48)

**Comment by tsujan** [comment]
@luis-pereira ?

**Comment by luis-pereira** [comment]
> Your correcting commit hasn't appeared in git.

Maybe, because I didn't made a PR. Only maybe ;)

**Comment by tsujan** [comment]
I was too hasty ;)

**Comment by luis-pereira** [comment]
@uncor3 Fixed. Thanks for the report.
